export type ProgressStep = {
  id?: string;
  activityId?: string | null;
  runId?: string;
  sequence?: number | null;
  eventType?: string | null;
  kind?: string | null;
  audience?: string | null;
  visibility?: "user" | "debug" | "internal" | string | null;
  display?: "primary" | "secondary" | "hidden" | string | null;
  phase?: string;
  label?: string;
  detail?: string;
  detailDelta?: string | null;
  message?: string;
  safeReasoningSummary?: string | null;
  summaryDelta?: string | null;
  evidenceNeeded?: string[];
  uncertainty?: string[];
  safetyNote?: string | null;
  operation?: string | null;
  actionType?: string | null;
  toolName?: string | null;
  currentAction?: string | null;
  observation?: string | null;
  observationDelta?: string | null;
  nextAction?: string | null;
  nextActionDelta?: string | null;
  relatedSearchQuery?: string | null;
  aggregate?: Record<string, unknown> | null;
  status?: string;
  startedAt?: string | null;
  endedAt?: string | null;
  durationMs?: number | null;
  elapsedMs?: number | null;
  files?: string[];
  command?: string | string[] | null;
  proposalId?: string | null;
};
